update

diff --git a/.github/workflows/bench.yml b/.github/workflows/bench.yml
--- a/.github/workflows/bench.yml
+++ b/.github/workflows/bench.yml
@@ -34,7 +34,7 @@ jobs:
 
       - name: Get data and update file
         run: |
-          OUTPUT="$(node ./utils/GenerateLatestData.js) || { echo 'Failed to generate latest data'; exit 1; }"
+          OUTPUT="$(node ./utils/GenerateLatestData.js) || { echo 'Failed to generate latest data.'; exit 1; }"
           if [ -n "$OUTPUT" ]; then
             echo "$OUTPUT" > ./website/public/data/latest.json
             
@@ -45,6 +45,7 @@ jobs:
             git push
           else
             echo "No data generated, skipping Git operations."
+            exit 1
           fi
 
   build-and-deploy-site:
